// <auto-generated />
namespace Team14_Final_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class applied : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(applied));
        
        string IMigrationMetadata.Id
        {
            get { return "201605060612491_applied"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
